### ISSUE TITLE
Не запускается 

### ISSUE THREAD

**Issue by antonazgarovich** [tadatuta/bem-express#1]
После установки всех зависимостей пишет так.
> Cannot find module '/home/user/workspace/my-project/organaizer/desktop.bundles/index/index.bemtree.js' Error: Cannot find module '/home/user/workspace/my-project/organaizer/desktop.bundles/index/index.bemtree.js'

После смены папки на common.blocks или положив файл root.bemtree и переименновав его выход уже такой.
> block is not defined ReferenceError: block is not defined

Что можно сделать?

**Comment by tadatuta** [comment]
Судя по логам, нужно вернуть как было и выполнить `npm run build` (дальше для пересборки можно использовать вотчер: `npm run watch`).

**Comment by antonazgarovich** [comment]
Спасибо сработало только команда ```npm run make```
